### ISSUE TITLE
Website URL does not behave properly

### ISSUE THREAD

**Issue by neon-code** [osqledaren/osqledaren-frontend#93]
I pressed English > Samhalle > English > Samhalle in succession and the website gives 404.

Check the URL. Instead of going to osqledaren.se/english after visiting Samhalle (osqledaren.se/samhalle), it goes to osqledaren.se/samhalle/english

Steps to recreate the problem are as above.

**Comment by adamsarnell** [comment]
Fixed! 
The bug was caused by not including "/" when creating the slugs in Sanity. No need for updating any code.

![slugs-issue](https://user-images.githubusercontent.com/46059361/133604842-4e696725-6893-4de2-b343-48b5c7ec9557.png)
